version: "3.9"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 're-play'
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432"


  app:
    build: "."
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      db_host: postgres
    volumes:
      - ./logs:/app/logs