# Generated by Django 4.2.1 on 2023-05-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferalBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=255, verbose_name='Имя БАТИ')),
                ('father_username', models.CharField(max_length=255, verbose_name='User_name БАТИ')),
                ('tg_id', models.BigIntegerField(verbose_name='Tg_id')),
                ('sb_id', models.BigIntegerField(verbose_name='Sb_id')),
                ('last_tg_id', models.BigIntegerField(verbose_name='Tg_id последнего')),
                ('count_referals', models.IntegerField(verbose_name='Количество рефералов')),
                ('last_username', models.CharField(max_length=255, verbose_name='User_name последнего')),
                ('invite_link', models.CharField(max_length=200, verbose_name='Пригласительная ссылка')),
                ('pred_invite_link', models.CharField(max_length=200, verbose_name='Ссылка по которой пришел ')),
            ],
            options={
                'verbose_name': 'Реферал',
                'verbose_name_plural': 'Рефералы',
            },
        ),
        migrations.CreateModel(
            name='UsersBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(verbose_name='ID Новичка')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('username', models.CharField(max_length=255, verbose_name='username')),
                ('invite_link', models.CharField(max_length=200, verbose_name='По какой ссылке пришел')),
            ],
            options={
                'verbose_name': 'Юзер',
                'verbose_name_plural': 'Юзеры',
            },
        ),
    ]
