# Generated by Django 4.2.1 on 2023-05-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersbase',
            name='father_id',
            field=models.BigIntegerField(default=1, verbose_name='ID Бати'),
            preserve_default=False,
        ),
    ]
